### ISSUE TITLE
Errors after updating ComfyUi

### ISSUE THREAD

**Issue by 631557fcd** [ExponentialML/ComfyUI_ModelScopeT2V#5]
After updating ComfyUi to 2590[5e806f] (2024-08-21) the following error prevents the node from loading:

ImportError: cannot import name 'sd2_clip' from 'comfy' (unknown location)

When i fix it via a symlinked copy of sd2_clip.py from ComfyUI/ComfyUI/comfy/text_encoders/ to ComfyUI/ComfyUI/comfy/ this error is prevented but gives another error:

`!!! Exception during processing !!! ModelPatcher.__init__() got an unexpected keyword argument 'current_device'
Traceback (most recent call last):
  File "/home/geistt/Applications/ComfyUI/ComfyUI/execution.py", line 316, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/geistt/Applications/ComfyUI/ComfyUI/execution.py", line 191, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/geistt/Applications/ComfyUI/ComfyUI/execution.py", line 168, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/geistt/Applications/ComfyUI/ComfyUI/execution.py", line 157, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/geistt/Applications/ComfyUI/ComfyUI/custom_nodes/ComfyUI_ModelScopeT2V/nodes.py", line 214, in load_modelscopet2v
    model = load_modelscope_checkpoint(
  File "/home/geistt/Applications/ComfyUI/ComfyUI/custom_nodes/ComfyUI_ModelScopeT2V/nodes.py", line 104, in load_modelscope_checkpoint
    model_patcher = comfy.model_patcher.ModelPatcher(
TypeError: ModelPatcher.__init__() got an unexpected keyword argument 'current_device'
`

**Comment by aivrar** [comment]
Same here.

**Comment by ColdFire87** [comment]
The easy fix is to go to `configs/modelscope_config.py` and replace

```python
from comfy import sd2_clip
```

with 

```python
from comfy.text_encoders import sd2_clip
```

For reference, this is the ComfyUI breaking change that caused the issue -> https://github.com/comfyanonymous/ComfyUI/commit/4ba7fa0244badcf901f2b8ddbfb8539c6398672f

**Comment by screan** [comment]
> The easy fix is to go to `configs/modelscope_config.py` and replace
> 
> ```python
> from comfy import sd2_clip
> ```
> 
> with
> 
> ```python
> from comfy.text_encoders import sd2_clip
> ```
> 
> For reference, this is the ComfyUI breaking change that caused the issue -> [comfyanonymous/ComfyUI@4ba7fa0](https://github.com/comfyanonymous/ComfyUI/commit/4ba7fa0244badcf901f2b8ddbfb8539c6398672f)

node loads now.. but getting error

- **Node Type:** ModelScopeT2VLoader
- **Exception Type:** TypeError
- **Exception Message:** ModelPatcher.__init__() got an unexpected keyword argument 'current_device'

**Comment by veryvanya** [comment]
anyone still not able to fix with latest comfy?

**Comment by soundboi123** [comment]
still havent found a fix?

**Comment by soundboi123** [comment]
i solved the issue for me, this is a temporary fix and i don't know if this break  anything, but for now its working for me:
in ComfyUI\custom_nodes\ComfyUI_ModelScopeT2V\nodes.py
change: current_device=inital_load_device
to: #current_device=inital_load_device
i just put the hashtag there because i dont wanna remove it incase it'll break some things. 

so simply deleting the argument worked for me, i hope it works for you guys too and if theres a better fix let me know!

and im very sorry for the messiness of my message, im new to github

**Comment by screan** [comment]
thanks @soundboi123 

got it running with these two fixes

go to configs/modelscope_config.py and replace:

from comfy import sd2_clip
with
from comfy.text_encoders import sd2_clip

in ComfyUI\custom_nodes\ComfyUI_ModelScopeT2V\nodes.py
change: current_device=inital_load_device
to: #current_device=inital_load_device

**Comment by soundboi123** [comment]
> thanks @soundboi123
> 
> got it running with these two fixes
> 
> go to configs/modelscope_config.py and replace:
> 
> from comfy import sd2_clip with from comfy.text_encoders import sd2_clip
> 
> in ComfyUI\custom_nodes\ComfyUI_ModelScopeT2V\nodes.py change: current_device=inital_load_device to: #current_device=inital_load_device

glad this works!
